language: python

sudo: true

python:
  - '2.7'

install:
- pip install --upgrade setuptools
- pip install -r requirements.txt
- pip install -r requirements-dev.txt

script:
- python ./setup.py develop && COMPILE='--compile' make check
