name: xdis (windows)

on:
  push:
    branches: [ python-3.1-to-3.2 ]
  pull_request:
    branches: [ python-3.1-to-3.2 ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [windows]
        python-version: [3.2]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -e .
        pip install -r requirements-dev.txt
    - name: Test xdis
      run: |
        make check
